# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0680c261111dce7388a0cb457415c14c9a3f780cb96b22ea1638148d92d1dafc9ab388f94f501f55e44eea274401afe1c3a0032eefd52a006fe5127aa23294bb

test:
  secret_key_base: f2b8ffa5e966839e715cc599a967a83f12c575274421a3ac593e55ba00b91011727354f76a9a8a28406e875f580cda253df9738106a3366d6ba244febca796d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
